<?php

namespace App\Resources\General\Methods;


use App\Resources\AbstractMethodRequest;

class Languages extends AbstractMethodRequest{

    public function executeFunction()
    {
        parent::executeFunction(); // TODO: Change the autogenerated stub
    }

}