version: '2'
services:
  mysql:
   image: mysql:5.7
   volumes:
   - ./_data/database/:/var/lib/mysql/
   - ./seeds/mysql:/seed
  #  - ./db/disable_strict_mode.cnf:/etc/mysql/conf.d/disable_strict_mode.cnf
   restart: always
   ports:
   - 3306:3306
   environment:
   - MYSQL_ROOT_PASSWORD=komparu_root
   - MYSQL_DATABASE=komparu
   - MYSQL_USER=komparu_db
   - MYSQL_PASSWORD=komparu
  
  nginx:
    image: nginx:1.13-alpine
    volumes:
    - ./src:/app/src
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - api
    links:
    - api
    ports:
    - "80:80"
    environment:
    - VIRTUAL_HOST="api-local.dig.network"
    - VIRTUAL_HOST_WEIGHT=1

  api:
    build:
      context: ./
      dockerfile: ./docker/phpfpm/Dockerfile
    volumes:
    - ./src:/app/src
    tty: true
    stdin_open: true
    depends_on: 
    - mysql
    links:
    - mysql
    command:
    - php-fpm7.0