<?php
/**
 * User: Roeland Werring
 * Date: 17/03/15
 * Time: 11:39
 *
 */

namespace App\Resources\Easyswitch\Methods\Impl;

use App\Helpers\ResourceFilterHelper;
use App\Interfaces\ResourceInterface;
use App\Resources\Easyswitch\Methods\EasyswitchAbstractRequest;

class EnergyCompare extends EasyswitchAbstractRequest
{

    private $extended = false;
    private $contract_ids = [];
    private $origParams;

    protected $cacheDays = false;

    protected $outputFields = [

        ResourceInterface::PRICE_DEFAULT,
        ResourceInterface::PRICE_SUPPLY,
        ResourceInterface::PRICE_SUPPLY_TOTAL,
        ResourceInterface::PRICE_TOTAL_VAT,
        ResourceInterface::PRICE_SAVINGS,
        ResourceInterface::PRICE_DISCOUNT,
        ResourceInterface::TOTAL_RATING,
        ResourceInterface::RATINGS,
        ResourceInterface::APPLY,
        ResourceInterface::CONTRACT_ID,
        ResourceInterface::CONTRACT_DURATION_MONHTS,
        ResourceInterface::CONTRACT_TYPE,
        ResourceInterface::ENERGY_TYPE,
        ResourceInterface::CONTRACT_ID,
        ResourceInterface::DISCOUNT_TEXT,
        ResourceInterface::DISCOUNT_TEXT_SHORT,
        ResourceInterface::HEADING,
        ResourceInterface::PROVIDER_NAME,
        ResourceInterface::PROVIDER_PHONE,
        ResourceInterface::PROVIDER_PHONE_COSTS,
        ResourceInterface::PROVIDER_EMAIL,
        ResourceInterface::PROVIDER_WEBSITE,
        ResourceInterface::PROVIDER_ACCEPTGIRO_COSTS,
        ResourceInterface::PROVIDER_LICENSEE,
        ResourceInterface::PROVIDER_STREET,
        ResourceInterface::PROVIDER_HOUSE_NUMBER,
        ResourceInterface::PROVIDER_SUFFIX,
        ResourceInterface::PROVIDER_POSTAL_CODE,
        ResourceInterface::PROVIDER_CITY,
        ResourceInterface::PROVIDER_CONDITIONS,
        ResourceInterface::CONTRACT_CONDITIONS,
        ResourceInterface::ELECTRICITY_TOTAL_COSTS,
        ResourceInterface::ELECTRICITY_NETWORK_COSTS,
        ResourceInterface::ELECTRICITY_TARRIF_HIGH,
        ResourceInterface::ELECTRICITY_TARRIF_LOW,
        ResourceInterface::ELECTRICITY_STANDING_CHARGE,
        ResourceInterface::ELECTRICITY_TAX,
        ResourceInterface::GAS_TARRIF,
        ResourceInterface::GAS_STANDING_CHARGE,
        ResourceInterface::GAS_TAX,
        ResourceInterface::GAS_TOTAL_COSTS,
        ResourceInterface::GAS_NETWORK_COSTS,
        ResourceInterface::DISCOUNT,
        ResourceInterface::DISCOUNT_DESCRIPTION,
        ResourceInterface::TOTAL_COSTS_NO_DISCOUNT,
        ResourceInterface::TOTAL_COSTS,
        ResourceInterface::TAX_DISCOUNT,
        ResourceInterface::ELECTRICITY_USAGE_TOTAL,
        //autogenerated
        'aanvragen_toegestaan',
        'aanvragen_url',
        'aanvragen_bestaandeKlanten',
        'aanvragen_nieuweKlanten',
        'aanbieder_generic_name',
        'aanbieder_generic_short_name',
        'aanbieder_generic_telephone',
        'aanbieder_generic_helpdesk_costs',
        'aanbieder_generic_fax',
        'aanbieder_generic_email',
        'aanbieder_generic_website',
        'aanbieder_generic_bank_number',
        'aanbieder_generic_comments_external',
        'aanbieder_generic_automated_delivery',
        'aanbieder_generic_automated_email',
        'aanbieder_generic_payment_methods',
        'aanbieder_generic_street_name',
        'aanbieder_generic_street_number',
        'aanbieder_generic_street_extension',
        'aanbieder_generic_zipcode',
        'aanbieder_generic_postal_free',
        'aanbieder_generic_postal_number',
        'aanbieder_generic_postal_zipcode',
        'aanbieder_generic_postal_city',
        'aanbieder_generic_postal_country_code',
        'aanbieder_generic_address_comments',
        'aanbieder_generic_overstap_proces_business_switch_1_tekst_kort',
        'aanbieder_generic_overstap_proces_business_switch_1_tekst_lang',
        'aanbieder_generic_overstap_proces_business_switch_1_type',
        'aanbieder_generic_overstap_proces_business_switch_1_resource_id',
        'aanbieder_generic_overstap_proces_business_switch_2_tekst_kort',
        'aanbieder_generic_overstap_proces_business_switch_2_tekst_lang',
        'aanbieder_generic_overstap_proces_business_switch_2_type',
        'aanbieder_generic_overstap_proces_business_switch_2_resource_id',
        'aanbieder_generic_overstap_proces_business_switch_3_tekst_kort',
        'aanbieder_generic_overstap_proces_business_switch_3_tekst_lang',
        'aanbieder_generic_overstap_proces_business_switch_3_type',
        'aanbieder_generic_overstap_proces_business_switch_3_resource_id',
        'aanbieder_generic_overstap_proces_business_switch_4_tekst_kort',
        'aanbieder_generic_overstap_proces_business_switch_4_tekst_lang',
        'aanbieder_generic_overstap_proces_business_switch_4_type',
        'aanbieder_generic_overstap_proces_business_switch_4_resource_id',
        'aanbieder_generic_overstap_proces_business_switch_5_tekst_kort',
        'aanbieder_generic_overstap_proces_business_switch_5_tekst_lang',
        'aanbieder_generic_overstap_proces_business_switch_5_type',
        'aanbieder_generic_overstap_proces_business_switch_5_resource_id',
        'aanbieder_generic_overstap_proces_business_move_1_tekst_kort',
        'aanbieder_generic_overstap_proces_business_move_1_tekst_lang',
        'aanbieder_generic_overstap_proces_business_move_1_type',
        'aanbieder_generic_overstap_proces_business_move_1_resource_id',
        'aanbieder_generic_overstap_proces_business_move_2_tekst_kort',
        'aanbieder_generic_overstap_proces_business_move_2_tekst_lang',
        'aanbieder_generic_overstap_proces_business_move_2_type',
        'aanbieder_generic_overstap_proces_business_move_2_resource_id',
        'aanbieder_generic_overstap_proces_business_move_3_tekst_kort',
        'aanbieder_generic_overstap_proces_business_move_3_tekst_lang',
        'aanbieder_generic_overstap_proces_business_move_3_type',
        'aanbieder_generic_overstap_proces_business_move_3_resource_id',
        'aanbieder_generic_overstap_proces_business_move_4_tekst_kort',
        'aanbieder_generic_overstap_proces_business_move_4_tekst_lang',
        'aanbieder_generic_overstap_proces_business_move_4_type',
        'aanbieder_generic_overstap_proces_business_move_4_resource_id',
        'aanbieder_generic_overstap_proces_business_move_5_tekst_kort',
        'aanbieder_generic_overstap_proces_business_move_5_tekst_lang',
        'aanbieder_generic_overstap_proces_business_move_5_type',
        'aanbieder_generic_overstap_proces_business_move_5_resource_id',
        'aanbieder_generic_overstap_proces_consument_switch_1_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_switch_1_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_switch_1_type',
        'aanbieder_generic_overstap_proces_consument_switch_1_resource_id',
        'aanbieder_generic_overstap_proces_consument_switch_2_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_switch_2_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_switch_2_type',
        'aanbieder_generic_overstap_proces_consument_switch_2_resource_id',
        'aanbieder_generic_overstap_proces_consument_switch_3_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_switch_3_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_switch_3_type',
        'aanbieder_generic_overstap_proces_consument_switch_3_resource_id',
        'aanbieder_generic_overstap_proces_consument_switch_4_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_switch_4_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_switch_4_type',
        'aanbieder_generic_overstap_proces_consument_switch_4_resource_id',
        'aanbieder_generic_overstap_proces_consument_switch_5_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_switch_5_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_switch_5_type',
        'aanbieder_generic_overstap_proces_consument_switch_5_resource_id',
        'aanbieder_generic_overstap_proces_consument_switch_6_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_switch_6_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_switch_6_type',
        'aanbieder_generic_overstap_proces_consument_switch_6_resource_id',
        'aanbieder_generic_overstap_proces_consument_move_1_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_move_1_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_move_1_type',
        'aanbieder_generic_overstap_proces_consument_move_1_resource_id',
        'aanbieder_generic_overstap_proces_consument_move_2_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_move_2_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_move_2_type',
        'aanbieder_generic_overstap_proces_consument_move_2_resource_id',
        'aanbieder_generic_overstap_proces_consument_move_3_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_move_3_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_move_3_type',
        'aanbieder_generic_overstap_proces_consument_move_3_resource_id',
        'aanbieder_generic_overstap_proces_consument_move_4_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_move_4_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_move_4_type',
        'aanbieder_generic_overstap_proces_consument_move_4_resource_id',
        'aanbieder_generic_overstap_proces_consument_move_5_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_move_5_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_move_5_type',
        'aanbieder_generic_overstap_proces_consument_move_5_resource_id',
        'aanbieder_generic_overstap_proces_consument_move_6_tekst_kort',
        'aanbieder_generic_overstap_proces_consument_move_6_tekst_lang',
        'aanbieder_generic_overstap_proces_consument_move_6_type',
        'aanbieder_generic_overstap_proces_consument_move_6_resource_id',
        'aanbieder_generic_resource_id',
        'aanbieder_generic_title',
        'aanbieder_generic_city',
        'aanbieder_energy_extrainfo_company_id',
        'aanbieder_energy_extrainfo_klantenbalies',
        'aanbieder_energy_extrainfo_vergunninghouder',
        'aanbieder_energy_extrainfo_lid_geschillencommissie',
        'aanbieder_energy_extrainfo_lid_gedragscode',
        'aanbieder_energy_extrainfo_antwoord_email',
        'aanbieder_energy_extrainfo_antwoord_brief',
        'aanbieder_energy_extrainfo_antwoord_telefoon',
        'aanbieder_energy_extrainfo_tijdigheid_rekening_electricity',
        'aanbieder_energy_extrainfo_tijdigheid_rekening_gas',
        'aanbieder_energy_extrainfo_signalen_klachten_algemeen',
        'aanbieder_energy_extrainfo_waarom_bijzonder',
        'aanbieder_energy_extrainfo_boete_opzeggen',
        'aanbieder_energy_extrainfo_boete_hoogte',
        'aanbieder_energy_extrainfo_acceptgiro_kosten',
        'aanbieder_energy_extrainfo_autoincasso_kosten',
        'aanbieder_energy_extrainfo_balie_kosten',
        'aanbieder_energy_extrainfo_betaalmogelijkheid_anders',
        'aanbieder_energy_extrainfo_kosten_eerste',
        'aanbieder_energy_extrainfo_kosten_tweede',
        'aanbieder_energy_extrainfo_kosten_verhuizen',
        'aanbieder_energy_extrainfo_kosten_overig',
        'aanbieder_energy_extrainfo_resource_id',
        'aanbieder_energy_label_percentage_groen',
        'aanbieder_energy_label_percentage_kolen',
        'aanbieder_energy_label_percentage_gas',
        'aanbieder_energy_label_percentage_kern',
        'aanbieder_energy_label_percentage_overig',
        'aanbieder_energy_label_percentage_wind',
        'aanbieder_energy_label_percentage_zon',
        'aanbieder_energy_label_percentage_water',
        'aanbieder_energy_label_percentage_bio',
        'aanbieder_energy_label_co2_per_kwh',
        'aanbieder_energy_label_radioactief_afval_per_kwh',
        'aanbieder_img',
        'aanbieder_title',
        'aanbieder_name',
        'bestaandeKlanten',
        'contract_looptijd',
        'contract_vrijOpzegbaar',
        'contract_tariefVast',
        'prijs_type',
        'prijs_prijzen_stroom_levering_totaal',
        'prijs_prijzen_stroom_levering_single_totaal_prijs',
        'prijs_prijzen_stroom_levering_single_totaal',
        'prijs_prijzen_stroom_levering_korting',
        'prijs_prijzen_stroom_levering_administratiekosten',
        'prijs_prijzen_stroom_levering_prijs',
        'prijs_prijzen_stroom_levering_belasting',
        'prijs_prijzen_stroom_levering_per_eenheid',
        'prijs_prijzen_stroom_levering_vastrecht',
        'prijs_prijzen_stroom_levering_hoog',
        'prijs_prijzen_stroom_levering_laag',
        'prijs_prijzen_stroom_levering_hoog_prijs',
        'prijs_prijzen_stroom_levering_laag_prijs',
        'prijs_prijzen_stroom_levering_jaar',
        'prijs_prijzen_stroom_levering_maand',
        'prijs_prijzen_stroom_transport_capaciteitstarief',
        'prijs_prijzen_stroom_transport_capaciteit',
        'prijs_prijzen_stroom_transport_capaciteitsprijs',
        'prijs_prijzen_stroom_transport_totaal',
        'prijs_prijzen_stroom_transport_aansluitkosten',
        'prijs_prijzen_stroom_transport_transportkosten',
        'prijs_prijzen_stroom_transport_meterhuur',
        'prijs_prijzen_stroom_transport_systeemdiensten_toeslag',
        'prijs_prijzen_stroom_belasting_per_eenheid',
        'prijs_prijzen_stroom_belasting_kortingtotaal',
        'prijs_prijzen_stroom_belasting_totaal',
        'prijs_prijzen_stroom_belasting_0_kortingtot',
        'prijs_prijzen_stroom_belasting_0_zonderkorting',
        'prijs_prijzen_stroom_belasting_0_prijs',
        'prijs_prijzen_gas_belasting_0_zonderkorting',
        'prijs_prijzen_gas_levering_totaal',
        'prijs_prijzen_gas_levering_korting',
        'prijs_prijzen_gas_levering_administratiekosten',
        'prijs_prijzen_gas_levering_prijs',
        'prijs_prijzen_gas_levering_belasting',
        'prijs_prijzen_gas_levering_per_eenheid',
        'prijs_prijzen_gas_levering_vastrecht',
        'prijs_prijzen_gas_levering_vastrechtkorting',
        'prijs_prijzen_gas_levering_jaar',
        'prijs_prijzen_gas_levering_maand',
        'prijs_prijzen_gas_transport_capaciteitstarief',
        'prijs_prijzen_gas_transport_capaciteit',
        'prijs_prijzen_gas_transport_capaciteitsprijs',
        'prijs_prijzen_gas_transport_totaal',
        'prijs_prijzen_gas_transport_aansluitkosten',
        'prijs_prijzen_gas_transport_transportkosten',
        'prijs_prijzen_gas_transport_meterhuur',
        'prijs_prijzen_gas_transport_systeemdiensten_toeslag',
        'prijs_prijzen_gas_belasting_total_price_kortingtot',
        'prijs_prijzen_gas_belasting_total_price_zonderkorting',
        'prijs_prijzen_gas_belasting_total_price_vanaf',
        'prijs_prijzen_gas_belasting_total_price_tot',
        'prijs_prijzen_gas_belasting_total_price_prijs',
        'prijs_prijzen_gas_belasting_total_price_totaal',
        'prijs_prijzen_gas_belasting_total_price_gebruik',
        'prijs_prijzen_gas_belasting_tax_price_per_m3_kortingtot',
        'prijs_prijzen_gas_belasting_tax_price_per_m3_zonderkorting',
        'prijs_prijzen_gas_belasting_tax_price_per_m3_vanaf',
        'prijs_prijzen_gas_belasting_tax_price_per_m3_tot',
        'prijs_prijzen_gas_belasting_tax_price_per_m3_prijs',
        'prijs_prijzen_gas_belasting_tax_price_per_m3_totaal',
        'prijs_prijzen_gas_belasting_tax_price_per_m3_gebruik',
        'prijs_prijzen_gas_belasting_per_eenheid',
        'prijs_prijzen_gas_belasting_kortingtotaal',
        'prijs_prijzen_gas_belasting_0_totaal',
        'prijs_prijzen_transport_totaal',
        'prijs_totaal',
        'prijs_btw',
        'prijs_jaar',
        'prijs_maand',
        'prijs_korting_totaal',
        'prijs_korting',
        'tekst_korting',
        'tekst_kortingKort',
        'tekst_opmerkingen',
        'producten_combi_product_plus',
        'producten_combi_tekst_korting',
        'producten_combi_tekst_kortingKort',
        'producten_combi_tekst_opmerkingen',
        'producten_combi_aanbieder_resource_id',
        'producten_combi_aanbieder_name',
        'producten_combi_aanbieder_title',
        'producten_combi_contract_looptijd',
        'producten_combi_contract_vrijOpzegbaar',
        'producten_combi_contract_tariefVast',
        'producten_combi_contract_boete',
        'producten_combi_contract_boeteStaffel',
        'producten_combi_groen',
        'producten_combi_resource_id',
        'producten_combi_name',
        'producten_stroom_product_plus',
        'producten_stroom_tekst_korting',
        'producten_stroom_tekst_kortingKort',
        'producten_stroom_tekst_opmerkingen',
        'producten_stroom_aanbieder_resource_id',
        'producten_stroom_aanbieder_name',
        'producten_stroom_aanbieder_title',
        'producten_stroom_contract_looptijd',
        'producten_stroom_contract_vrijOpzegbaar',
        'producten_stroom_contract_tariefVast',
        'producten_stroom_contract_boete',
        'producten_stroom_contract_boeteStaffel_under_1_year',
        'producten_stroom_voorwaarden_1',
        'producten_stroom_groen',
        'producten_stroom_energielabel_percentage_groen',
        'producten_stroom_energielabel_percentage_grijs',
        'producten_stroom_energielabel_percentage_kolen',
        'producten_stroom_energielabel_percentage_gas',
        'producten_stroom_energielabel_percentage_kern',
        'producten_stroom_energielabel_percentage_overig',
        'producten_stroom_energielabel_percentage_wind',
        'producten_stroom_energielabel_percentage_zon',
        'producten_stroom_energielabel_percentage_water',
        'producten_stroom_energielabel_percentage_bio',
        'producten_stroom_energielabel_co2_per_kwh',
        'producten_stroom_energielabel_radioactief_afval_per_kwh',
        'producten_stroom_energielabel_resource_id',
        'producten_stroom_resource_id',
        'producten_stroom_name',
        'producten_gas_product_plus',
        'producten_gas_tekst_korting',
        'producten_gas_tekst_kortingKort',
        'producten_gas_tekst_opmerkingen',
        'producten_gas_aanbieder_resource_id',
        'producten_gas_aanbieder_name',
        'producten_gas_aanbieder_title',
        'producten_gas_contract_looptijd',
        'producten_gas_contract_vrijOpzegbaar',
        'producten_gas_contract_tariefVast',
        'producten_gas_contract_boete',
        'producten_gas_groen',
        'producten_gas_resource_id',
        'producten_gas_name',
        'actievoorwaarden_actievoorwaarden_aug_2015_1_jaar_pdf_name',
        'actievoorwaarden_actievoorwaarden_aug_2015_1_jaar_pdf_path',
        'actievoorwaarden_actievoorwaarden_aug_2015_1_jaar_pdf_url',
        'voorwaarden_algemene voorwaarden 1 aug 2013_pdf_name',
        'voorwaarden_algemene voorwaarden 1 aug 2013_pdf_path',
        'voorwaarden_algemene voorwaarden 1 aug 2013_pdf_url',
        'prijs_display_stroom_verbruik_totaal_label',
        'prijs_display_stroom_verbruik_totaal_value',
        'prijs_display_stroom_verbruik_totaal_display',
        'prijs_display_stroom_netwerk_totaal_label',
        'prijs_display_stroom_netwerk_totaal_value',
        'prijs_display_stroom_netwerk_totaal_display',
        'prijs_display_gas_verbruik_totaal_label',
        'prijs_display_gas_verbruik_totaal_value',
        'prijs_display_gas_verbruik_totaal_display',
        'prijs_display_gas_netwerk_totaal_label',
        'prijs_display_gas_netwerk_totaal_value',
        'prijs_display_gas_netwerk_totaal_display',
        'prijs_display_totaal_korting_jaar_label',
        'prijs_display_totaal_korting_jaar_value',
        'prijs_display_totaal_korting_jaar_display',
        'prijs_display_totaal_jaar_geen_korting_label',
        'prijs_display_totaal_jaar_geen_korting_value',
        'prijs_display_totaal_jaar_geen_korting_display',
        'prijs_display_totaal_jaar_label',
        'prijs_display_totaal_jaar_value',
        'prijs_display_totaal_jaar_display',
        'prijs_display_totaal_maand_label',
        'prijs_display_totaal_maand_value',
        'prijs_display_totaal_maand_display',
        'prijs_prijzen_levering_totaal',
        'prijs_besparing',
        'producten_stroom_type',
        'producten_gas_type',
        'stroom_tarieven',
        'gas_tarieven',
        'doelgroep',
        'type_meter',
        'prijs_prijzen_gas_transport_netbeheerder',
        'prijs_prijzen_stroom_transport_netbeheerder',
        'prijs_prijzen_stroom_belasting_0_tarief',
        'prijs_prijzen_stroom_belasting_0_tarief_ode',
        'prijs_prijzen_stroom_belasting_1_tarief',
        'prijs_prijzen_stroom_belasting_1_tarief_ode',
        'stroom_ode_0_totaal',
        'stroom_ode_1_totaal',
        'prijs_prijzen_stroom_belasting_0_verbruik',
        'prijs_prijzen_stroom_belasting_1_verbruik',
        'prijs_prijzen_stroom_belasting_subtotaal',
        'prijs_prijzen_stroom_belasting_totaal_korting',
        'stroom_energiebelasting_0_totaal',
        'stroom_energiebelasting_1_totaal',
        'prijs_prijzen_gas_belasting_0_tarief',
        'prijs_prijzen_gas_belasting_0_tarief_ode',
        'prijs_prijzen_gas_belasting_subtotaal',
        'prijs_prijzen_gas_belasting_totaal_korting',
        'gas_ode_totaal',
        'gas_energiebelasting_totaal',
        'prijs_prijzen_stroom_levering_hoog_prijs',
        'prijs_prijzen_stroom_levering_laag_prijs',
        'prijs_prijzen_stroom_levering_hoog_totaal',
        'prijs_prijzen_stroom_levering_laag_totaal',
        'prijs_prijzen_stroom_levering_hoog_totaal_prijs',
        'prijs_prijzen_stroom_levering_laag_totaal_prijs',
        'prijs_prijzen_gas_levering_single_totaal',
        'prijs_prijzen_gas_levering_single_totaal_prijs',
        'price_admin',
        'price_admin_flag',
        'discount_flag',
    ];


    protected $arguments = [
        ResourceInterface::POSTAL_CODE              => [
            'rules'   => self::VALIDATION_REQUIRED_POSTAL_CODE,
            'example' => '8014EH',
            'filter'  => 'filterToUppercase'
        ],
        ResourceInterface::HOUSE_NUMBER             => [
            'rules'   => 'required | integer',
            'example' => '21'
        ],
        ResourceInterface::SUFFIX                   => [
            'rules'   => 'string',
            'example' => '1E'
        ],
        ResourceInterface::CONTRACT_DURATION_MONHTS => [
            'rules'   => 'in:no_preference,continuously,12,24,36,48,60',
            'example' => 'fixed',
            'default' => 'no_preference'
        ],
        ResourceInterface::TARIFF_TYPE              => [
            'rules'   => 'in:fixed,variable,no_preference',
            'example' => 'fixed',
            'default' => 'no_preference'
        ],
        ResourceInterface::CURRENT_PROVIDER         => [
            'rules'           => self::VALIDATION_EXTERNAL_CHOICE,
            'external_choice' => [
                'resource' => 'energy',
                'method'   => 'products',
                'params'   => ['add_no_choice' => true],
                'key'      => ResourceInterface::RESOURCE_ID,
                'val'      => ResourceInterface::TITLE,
            ],
            'default'         => '-1'
        ],
        ResourceInterface::ENERGY_TYPE              => [
            'rules'   => 'in:green-green,green-grey,grey-grey,no_preference',
            'example' => 'green',
            'default' => 'no_preference'
        ],
        ResourceInterface::ELECTRICITY_USAGE_HIGH   => [
            'rules'   => 'required | integer',
            'example' => '5400',
        ],
        ResourceInterface::ELECTRICITY_USAGE_LOW    => [
            'rules'   => 'integer',
            'example' => '5400, only needed when double meter',
            'default' => '0'
        ],
        ResourceInterface::GAS_USAGE                => [
            'rules'   => 'integer | required',
            'example' => '5400',
        ],
        ResourceInterface::BUSINESS                 => [
            'rules'   => self::VALIDATION_BOOLEAN,
            'default' => 'false'
        ],
        ResourceInterface::CONTRACT_ID              => [
            'rules'   => 'array',
            'example' => '[12271-9195-11733,11705-8685-11173]',
        ],
        ResourceInterface::DUMP_FIELDS              => [
            'rules'   => self::VALIDATION_BOOLEAN,
            'default' => 0,
        ],


    ];


    public function __construct()
    {
        parent::__construct('/vergelijking/');
        $this->documentRequest      = true;
        $this->strictStandardFields = false;
    }

    public function setParams(Array $params)
    {
        $error = [];
        $totalElecUsage     = ResourceFilterHelper::array_get($params, 'verbruik_stroom_1') + ResourceFilterHelper::array_get($params, 'verbruik_stroom_2');
        $gasUsage = ResourceFilterHelper::array_get($params, 'verbruik_gas');
        if ($totalElecUsage == 0 && $gasUsage == 0) {
            $error['Verbruik'] = "Stroom- of gasverbruik moet meer zijn dan 0";
        }
        if ($totalElecUsage >= 100000 ) {
            $error['Verbruik stroom'] = "Stroomverbruik kan niet meer zijn dan 100.000 kwh per jaar";
        }
        if ($gasUsage >= 170000 ) {
            $error['Verbruik gas'] = "Gasverbruik kan niet meer zijn dan 170.000 m3 per jaar";
        }
        if(count($error) > 0){
            $this->setErrorString($error);
            return;
        }

        if(isset($params[ResourceInterface::CONTRACT_ID])){
            $this->extended     = true;
            $this->contract_ids = is_array($params[ResourceInterface::CONTRACT_ID]) ? $params[ResourceInterface::CONTRACT_ID] : explode(',', $params[ResourceInterface::CONTRACT_ID]);
        }
        parent::setParams($params);
    }

    public function getResult()
    {
        //{"fixed":{"36":45,"12":40},"variable":{"12":30}}
        //        $arr[] = ['contract_type'=> 'fixed','contract_duration_monhts' => 36, '@value' => 45];
        //        $arr[] = ['contract_type'=> 'fixed','contract_duration_monhts' => 12, '@value' => 40];
        //        $arr[] = ['contract_type'=> 'variable','contract_duration_monhts' => 12, '@value' => 12];
        //        die(json_encode($arr));
        $resArr = [];
        $result = parent::getResult()[0];

        if(!isset($result['producten'])){
            $this->meta = $result;
            return [];
        }

        //products is result, rest is meta data
        $products = $result['producten'];

        $vrijopzegbaararr= [];

        foreach($products as $res){

            //set based on debug setting
            $newRes = [];



            $newRes[ResourceInterface::PRODUCT_TYPE]  = $res['type'];
            $newRes[ResourceInterface::CONTRACT_TYPE] = ($res['contract']['tariefVast'] == false) ? ResourceInterface::VARIABLE : ResourceInterface::FIXED;


            $newRes[ResourceInterface::HEADING] = $res['naam'];

            $newRes[ResourceInterface::PRICE_DEFAULT]      = $res['prijs']['maand'];
            $newRes[ResourceInterface::PRICE_SUPPLY]       = $res['prijs']['levering'];
            $newRes[ResourceInterface::PRICE_SUPPLY_TOTAL] = $res['prijs']['leveringTotaal'];
            $newRes[ResourceInterface::PRICE_TOTAL_VAT]    = $res['prijs']['totaalIncBtw'];
            $newRes[ResourceInterface::PRICE_SAVINGS]      = $res['prijs']['besparing'];
            $newRes[ResourceInterface::PRICE_DISCOUNT]     = $res['prijs']['korting'];

            $newRes[ResourceInterface::CONTRACT_DURATION_MONHTS] = $res['contract']['looptijd'];
            if ($newRes[ResourceInterface::CONTRACT_DURATION_MONHTS] == 0) {
                $newRes[ResourceInterface::CONTRACT_DURATION_MONHTS] = 'undetermined';
            }
            $newRes[ResourceInterface::DISCOUNT_TEXT]            = $res['tekst']['korting'];
            $newRes[ResourceInterface::DISCOUNT_TEXT_SHORT]      = $res['tekst']['kortingKort'];
            $newRes[ResourceInterface::APPLY]                    = $res['aanvragen']['toegestaan'];

            if (!$newRes[ResourceInterface::APPLY]) {
                continue;
            }

            //stroom
            if($newRes[ResourceInterface::PRODUCT_TYPE] == 'stroom'){
                $newRes[ResourceInterface::CONTRACT_ID] = '--' . $res[ResourceInterface::ID];
                $newRes[ResourceInterface::ENERGY_TYPE] = ($res['groen']) ? 'green-green' : 'grey-grey';
            }

            //gas
            if($newRes[ResourceInterface::PRODUCT_TYPE] == 'gas'){

                if($this->gasType == 'green' && ( ! isset($res['groen']) || ! $res['groen'])){
                    continue;
                }
                if($this->gasType == 'grey' && (isset($res['groen']) && $res['groen'])){
                    continue;
                }
                $newRes[ResourceInterface::CONTRACT_ID] = '-' . $res[ResourceInterface::ID].'-';
                $newRes[ResourceInterface::ENERGY_TYPE] = (isset($res['groen']) && $res['groen']) ? 'green-green' : 'grey-grey';
            }

            //combi
            if($newRes[ResourceInterface::PRODUCT_TYPE] == 'combi'){

                //comma seperated id, fucking awesome
                $newRes[ResourceInterface::CONTRACT_ID] = $res[ResourceInterface::ID] . '-' . $res['producten']['gas'][ResourceInterface::ID] . '-' . $res['producten']['stroom'][ResourceInterface::ID];


                if($this->gasType == 'green' && ! $res['producten']['gas']['groen']){
                    continue;
                }
                if($this->gasType == 'grey' && $res['producten']['gas']['groen']){
                    continue;
                }


                if($res['producten']['stroom']['groen']){
                    if($res['producten']['gas']['groen']){
                        $newRes[ResourceInterface::ENERGY_TYPE] = 'green-green';
                    }else{
                        $newRes[ResourceInterface::ENERGY_TYPE] = 'green-grey';
                    }
                }else{
                    $newRes[ResourceInterface::ENERGY_TYPE] = 'grey-grey';
                }
            }
            //add all results as underscore
            $flattenRes = $this->flattenUnderscore($res);
            $newRes     = array_merge($flattenRes, $newRes);


            //skip shit if extended
            if($this->extended){
                if( ! in_array($newRes[ResourceInterface::CONTRACT_ID], $this->contract_ids)){
                    //cw($newRes[ResourceInterface::CONTRACT_ID].' != '.print_r($this->contract_ids, true));
                    continue;
                }
                //cw($newRes[ResourceInterface::CONTRACT_ID].' == '.print_r($this->contract_ids, true));
                $params                                 = $this->origParams;
                $params[ResourceInterface::CONTRACT_ID] = $res[ResourceInterface::ID];
                $resInternal                            = $this->internalRequest($this->getRequestType(), 'details', $params);
                $newRes                                 = array_merge($newRes, $resInternal);
                if($this->params[ResourceInterface::DUMP_FIELDS] == 1){

                    //use the flatten array, this is plain stupid

                }

            }

            //get resource id
            $newRes[ResourceInterface::RESOURCE_ID] = $res['aanbieder'][ResourceInterface::ID];

            //Detail NL hardcoded
            $newRes['doelgroep']  = (isset($this->params['klant_type']) && ($this->params['klant_type']=='zakelijk')) ? 'Zakelijk' : 'Huishoudelijk';
            $newRes['type_meter'] = (isset($this->params['verbruik_stroom_2']) && $this->params['verbruik_stroom_2'] > 0) ? 'Dubbele meter' : 'Enkele meter';
            $resArr[] = $newRes;
        }

        unset($result['producten']);
        $this->meta = $result;
        return $resArr;
    }

    public function filterParamKeys(Array $params)
    {
        $this->origParams = $params;
        return parent::compareFilterParamKeys($params);
    }

    private function dumpFields($result, $level = '')
    {
        $resString = [];
        if(is_array($result)){
            foreach($result as $key => $element){
                if($key == ''){
                    continue;
                }
                $newKey = $level == '' ? $key : $level . '.' . $key;
                $str    = $this->dumpFields($element, $newKey);

                if(is_array($str)){
                    $resString = array_merge($resString, $str);
                }else{
                    $resString[] = "'" . $str . "'";
                }
            }
            return $resString;
        }
        return $level;
    }
    //         "contract_vrijOpzegbaar": true,
    //"contract_tariefVast": true,

    private function dumpFieldsType($result, $level = '')
    {
        $resString = [];
        if(is_array($result)){
            foreach($result as $key => $element){
                if($key == ''){
                    continue;
                }
                $newKey = $level == '' ? $key : $level . '.' . $key;
                $str    = $this->dumpFieldsType($element, $newKey);

                if(is_array($str)){
                    $resString = array_merge($resString, $str);
                }
            }
            return $resString;
        }
        if(is_float($result)){
            $type = 'price';
        }else if(is_int($result)){
            $type = 'integer';
        }else if(strlen($result) < 100){
            $type = 'string';
        }else{
            $type = 'text';
        }
        return [$level => $type];
    }

    /**
     * Flatten and transform to underscore
     *
     * @param $res
     *
     * @return array
     */
    protected function flattenUnderscore($res)
    {
        $flattenRes = [];
        foreach(array_dot($res) as $fKey => $kValue){
            $flattenRes[str_replace('.', '_', $fKey)] = $kValue;
        }
        return $flattenRes;
    }
}