<?php
/**
 * User: Roeland Werring
 * Date: 17/03/15
 * Time: 11:39
 *
 */

namespace App\Resources\Easyswitch\Methods\Impl;

use App\Interfaces\ResourceInterface;
use App\Resources\Easyswitch\Methods\EasyswitchAbstractRequest;

class EnergyLocations extends EasyswitchAbstractRequest
{
    private $housenumber;

    protected $arguments = [
        ResourceInterface::POSTAL_CODE  => [
            'rules'   => self::VALIDATION_REQUIRED_POSTAL_CODE,
            'example' => '8014EH',
            'filter'  => 'filterToUppercase'
        ],
        ResourceInterface::HOUSE_NUMBER => [
            'rules'   => 'required | integer',
            'example' => '21'
        ]
    ];

    public function setParams(Array $params)
    {
        $this->housenumber = $params['adres_huisnummer'];
        parent::setParams($params); // TODO: Change the autogenerated stub
    }

    public function getResult()
    {
        $result = parent::getResult()[0];
        $connections = isset($result['connections'])?$result['connections']:[];
        $result['connections'] = [];
        $result['suffixes'] = [];
        foreach($connections as $connection) {
            $result['connections'][] = $connection['toevoeging'];
            $label = $result['street'].' '.$this->housenumber.' '.$connection['toevoeging'];
            $result['suffixes'][] = ['name' => $connection['toevoeging'], 'label' => $label];
        }
        return $result;

    }

    public function __construct()
    {
        parent::__construct('/locaties/');
    }
}